### ISSUE TITLE
[dglo on 2013-08-23 15:02:08] : pDAQ: FileDispatcher bug leads to data loss

### ISSUE THREAD

**Issue by dglo** [dglo/eventBuilder-prod#123]
During run 122898, the eventBuilder started spitting out a stack trace for every event:

eventBuilder icecube.daq.eventBuilder.backend.EventBuilderBackEnd-EventWriter ERROR [2013-08-23 02:56:35.770] Could not dispatch event
icecube.daq.io.DispatchException: java.io.IOException: Bad file descriptor
	at icecube.daq.io.FileDispatcher.dispatchEvent(FileDispatcher.java:212)
	at icecube.daq.io.FileDispatcher.dispatchEvent(FileDispatcher.java:258)
	at icecube.daq.eventBuilder.backend.EventBuilderBackEnd$OutputThread.sendToDaqDispatch(EventBuilderBackEnd.java:1628)
	at icecube.daq.eventBuilder.backend.EventBuilderBackEnd$OutputThread.run(EventBuilderBackEnd.java:1586)
	at java.lang.Thread.run(Thread.java:736)
Caused by: java.io.IOException: Bad file descriptor
	at sun.nio.ch.FileDispatcher.write0(Native Method)
	at sun.nio.ch.FileDispatcher.write(FileDispatcher.java:39)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:104)
	at sun.nio.ch.IOUtil.write(IOUtil.java:75)
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:202)
	at icecube.daq.io.FileDispatcher.dispatchEvent(FileDispatcher.java:206)
	... 4 more

**Comment by dglo** [comment]
[dglo on 2013-08-26 23:48:12]
svn commit -m"Issue 6642: Abort output thread after 5 consecutive DispatchExceptions or 20 total DispatchExceptions"
Sending        src/main/java/icecube/daq/eventBuilder/backend/EventBuilderBackEnd.java
Sending        src/test/java/icecube/daq/eventBuilder/backend/EventBuilderBackEndTest.java
Sending        src/test/java/icecube/daq/eventBuilder/test/MockDispatcher.java
Transmitting file data ...
Committed revision 14595.

**Comment by dglo** [comment]
[dglo on 2014-01-20 21:11:43]
Furthermore has been running for several months
